services:
  - type: web
    name: smart-farmer-procurement
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PROJECT_NAME
        value: Smart Farmer Procurement Management System
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_USERNAME
        value: abhisheksanke999@gmail.com
      - key: SMTP_PASSWORD
        value: jgla ooje fzes plqp
      - key: SMTP_FROM
        value: abhisheksanke999@gmail.com
      - key: SMTP_USE_TLS
        value: "false"
      - key: RESEND_API_KEY
        sync: false


